### ISSUE TITLE
[0.2.0] Missing typescript definition files

### ISSUE THREAD

**Issue by dagatsoin** [blablacar/ui-library#10]
Actually Typescript has not access to the definition file because there is no `types` field in the package.json

Is it possible to add `field: /path/to/d.ts` in the package.json ?

**Comment by grosbouddha** [comment]
The types field has been filled in the manifest and points at the monolithic .d.ts for the whole library.
As well, we generate  granular .d.ts file for every class now too. These d.ts are embedded in the transpiled artifact and should be picked up automatically by the TypeScript compiler.
