### ISSUE TITLE
Broken icons on storybook

### ISSUE THREAD

**Issue by loick** [blablacar/ui-library#1014]
**Describe the bug**
👋 the icons page on storybook is broken

**To Reproduce**
https://blablacar.github.io/ui-library/?path=/story/design-tokens--icons

**Expected behavior**
It should be working.

**Screenshots**
Just go to the page, open the dev tools, select screenshot and you will have it 👍 

**Desktop (please complete the following information):**
Minitel

**Additional context**
It's chilly today isn't it?

**Comment by gabrielagabriel** [comment]
Hello @loick. Thanks for reporting the bug! We are going to take care of it. 
Meanwhile, you can use the [Docs Tab](https://blablacar.github.io/ui-library/?path=/docs/design-tokens--icons) for that.

By the way, did you like the new Storybook written on MDX? It's quite charming, isn't it?
