### ISSUE TITLE
Pass down the bodyClassName to the AutoCompleteList

### ISSUE THREAD

**Issue by dagatsoin** [blablacar/ui-library#14]
Currently it is not possible to pass a class to the result panel of the AutoCompletion component. So we need to use the `.kirk-autoComplete-list` accessor which may change in the futur and may break the app style.

**Current behavior:**
The property `bodyClassName` is passed down to the loading/noresult panel but not to the AutoCompleteList component.

**Expected behavior:**
The property `bodyClassName` is passed down to the AutoCompleteList component.

**Comment by Zarthia** [comment]
Fixed in v0.2.2

**Comment by pith** [comment]
Fixed here #18
