### ISSUE TITLE
How to modify colors?

### ISSUE THREAD

**Issue by chabou** [blablacar/ui-library#19]
What is the best way to customize colors?

I tried to do:
```
import {branding} from '@blablacar/ui-library'

branding.updateColor({
  primary: '#61BFD1',
  accent: '#61BFD1'
})
```

Colors output with `console.log(branding.color);` reflect my changes.
But component (Button for example), keeps its original color.

I'm trying to use your lib with NextJS.

**Comment by loick** [comment]
Hi there, 

We are currently working on the new system of color updates, and we forgot to deprecate this one. 
Sorry, I will ping you on this issue when we will rollout the new theming system.
