### ISSUE TITLE
Did you vue that?

### ISSUE THREAD

**Issue by loick** [blablacar/ui-library#282]
Hi everyone, 

I love what you did there, I really do. However I would like to have it in vueJS with a different theme, is it possible? Thanks! 

Keep it up 💪

**Comment by Tip-Sy** [comment]
Ohh! 😍
Yes I vue! 😂

**Comment by wakooka** [comment]
Yes and PRs are welcome. Can't wait to review it. :)

Le jeu. 27 juin 2019 à 17:22, Loick Le Digabel <notifications@github.com> a
écrit :

**Comment by Bidjii** [comment]
What about Angular though?
Asking for a friend

**Comment by loick** [comment]
Should we do separated Issues @Bidjii? Or should we gather all the framework needs we have here?

**Comment by grosbouddha** [comment]
I would love a flutter version too; can we use some switch/case technology to solve this trivially ?

**Comment by PerrineBoissieres** [comment]
And what about as a jQuery library? I need it to complete my Bootstrap website.
