### ISSUE TITLE
SSR is broken since v0.4.1

### ISSUE THREAD

**Issue by chabou** [blablacar/ui-library#42]
**Describe the bug**
I am using your `ui-library` with NextJS.
Since v0.4.1, SSR is not working anymore. The result is a first (server-side) rendering without any style. Styled are applied after JS loading.

I noticed that 0.4.1 has some dependencies updates, but it seems unrelated. I tried to build from sources and even at previous commit (v3.0.0 for exemaple), my problem occurs. NPM doesn't enforce very well dependencies version, even with a `package-lock.json`. I suspect that this problem is related to a dependency of a dependency.

**To Reproduce**
I can bootstrap a sample project if you want to tackle this issue

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4
 - Browser Chrome (67.0.3396.87) and Firefox (61.0.1)

**Comment by loick** [comment]
Hi,

We are using the design system on this page for instance, and this seems to be okay:
view-source:https://www.blablacar.fr/login/email

Agreed on the package-lock, we'll investigate on this. But if you have an example, it can be useful indeed.

Thanks for reporting!

**Comment by chabou** [comment]
I made an example to help you to reproduce: https://github.com/chabou/ui-library-test-ssr

**Comment by chabou** [comment]
In my previous workaround, I used `flushToHTML()` because `flush` export is broken. See https://github.com/blablacar/ui-library/pull/68

**Comment by wakooka** [comment]
Fixed in #68
