### ISSUE TITLE
Need to put an icon in AutoComplete component

### ISSUE THREAD

**Issue by dagatsoin** [blablacar/ui-library#5]
I need to show a "search" icon in the AutoComplete component. This should be done by passing a string representing the icon name or a render prop.

```
<AutoComplete icon="search"/>
<AutoComplete icon={() => <i class="...">}/>
```

**Comment by PerrineBoissieres** [comment]
Hi! You can use the `inputAddon` prop to pass any component as a left-addon (similar to the TextField component): 

```
<AutoComplete inputAddon={<IconSearch />} />
```

**Comment by pith** [comment]
Sample here: https://github.com/blablacar/ui-library/blob/master/src/autoComplete/story.tsx#L97
